source("_setup_corpora.R")
cat("names(biblio_metrics):", paste(names(biblio_metrics(x_analise)), collapse = ", "), "\n")
bm <- biblio_metrics(x_analise)
cat("dimensoes do elemento de autores:\n"); print(dim(bm$author))
print(head(bm$author, 3))
cat("\nterm_frequency com stopwords:\n")
tf <- term_frequency(x_analise, field = "title", stopwords = c("estudo"))
print(head(tf, 6))
cat("\nterm_frequency sem stopwords (top 3):\n")
print(head(term_frequency(x_analise, field = "title"), 3))
cat("\nfiltro de tokens numericos:\n")
tf2 <- tf[!grepl("^[0-9]+$", tf$term), ]
print(head(tf2, 8))
cat("\ntfidf com filtro:\n")
ti <- tfidf_terms(x_analise, group = "year")
ti <- ti[!grepl("^[0-9]+$", ti$term) & !ti$term %in% c("estudo"), ]
print(head(ti[order(-ti$tfidf), ], 8))
cat("\nnames(describe_biblio):", paste(names(describe_biblio(x_analise)), collapse = ", "), "\n")
cat("names(network_centrality):", paste(names(network_centrality(
  bibliographic_network(x_analise, "coauthor"))), collapse = ", "), "\n")
cat("names(term_frequency):", paste(names(tf), collapse = ", "), "\n")
cat("names(trend_topics):", paste(names(trend_topics(x_analise)), collapse = ", "), "\n")
cat("names(compare_sources):", paste(names(compare_sources(x_analise, x_did)), collapse = ", "), "\n")
cat("names(biblio_health):", paste(names(biblio_health(x_bruto)), collapse = ", "), "\n")
cat("names(network_stability):", paste(names(network_stability(x_analise, B = 5, seed = 1)), collapse = ", "), "\n")
cat("names(sensitivity_analysis):", paste(names(sensitivity_analysis(x_analise, g_per, thresholds = 1:2, permutations = 49, seed = 1)), collapse = ", "), "\n")
cat("names(run_plan(...)):", paste(names(run_plan(form_plan(analyses = c("health","network")), x_analise)), collapse = ", "), "\n")
cat("classe biblio_report? "); r <- biblio_report(x_analise, file.path(tempdir(), "r.md")); cat(class(r), "\n")
