## _receitas.R - verifica todas as receitas de chamada usadas nos módulos
source("_setup_corpora.R")
ck <- function(rotulo, expr) {
  cat("\n##### ", rotulo, "\n", sep = "")
  r <- tryCatch(expr, error = function(e) paste("ERRO:", conditionMessage(e)))
  if (is.character(r) && length(r) == 1 && grepl("^ERRO", r)) {
    cat(r, "\n")
  } else if (is.list(r) && !is.data.frame(r)) {
    cat("classe:", class(r)[1], "| elementos:", paste(utils::head(names(r), 8), collapse = ", "), "\n")
    utils::str(r, max.level = 1, give.attr = FALSE)
  } else {
    print(utils::head(as.data.frame(r), 4))
  }
  invisible(r)
}
cat("\n========== M1 ==========\n")
ck("structure", vapply(x_analise, nrow, integer(1)))
cat("\n========== M2 ==========\n")
ck("biblio_health bruto", biblio_health(x_bruto))
ck("health limpo", biblio_health(x_limpo))
ck("dedup log", attr(x_limpo, "dedup_log")[, c("title","doi")])
ck("audit_biblio", audit_biblio(x_bruto))
cat("\n========== M3 ==========\n")
ck("describe_biblio", describe_biblio(x_analise))
ck("biblio_metrics autores", biblio_metrics(x_analise)$authors)
ck("normalized_citations", normalized_citations(x_analise, strata = c("year","source")))
cat("\n========== M4 ==========\n")
ck("temporal_growth", temporal_growth(x_analise))
ck("citation_velocity", citation_velocity(x_analise))
ck("citation_trajectory", citation_trajectory(x_analise))
ck("rpys", rpys(reference_years = sample(1990:2015, 60, TRUE)))
ck("disruption_index", disruption_index("f", data.frame(citing_id = c("a","b"), cited_id = c("f","f")), "r1"))
cat("\n========== M5 ==========\n")
ck("term_frequency title", term_frequency(x_analise, field = "title"))
ck("tfidf_terms year", tfidf_terms(x_analise, group = "year"))
ck("trend_topics", trend_topics(x_analise))
cat("\n========== M6 ==========\n")
ck("compare_groups periodo", compare_groups(x_analise, g_per, entity = "keyword", permutations = 499, seed = SEED))
ck("compare_groups tema", compare_groups(x_analise, g_tema, entity = "keyword", permutations = 499, seed = SEED))
ck("association_residuals", association_residuals(compare_groups(x_analise, g_per, entity = "keyword", permutations = 499, seed = SEED)))
ck("group_ca", group_ca(compare_groups(x_analise, g_tema, entity = "keyword", permutations = 99, seed = SEED)))
ck("group_mca", group_mca(x_analise, g_tema, entity = "keyword")$eig)
ck("sensitivity_analysis", sensitivity_analysis(x_analise, g_per, thresholds = 1:3, permutations = 199, seed = SEED))
ck("compare_sources", compare_sources(x_analise, x_did)$coverage)
cat("\n========== M7 ==========\n")
gco <- bibliographic_network(x_analise, "coauthor")
ck("rede coauthor", data.frame(V = igraph::vcount(gco), E = igraph::ecount(gco)))
ck("network_centrality", network_centrality(gco))
ck("network_communities", network_communities(gco, "louvain"))
ck("network_stability", network_stability(x_analise, type = "coauthor", B = 20, seed = SEED))
ck("export_vosviewer", { f <- tempfile(fileext = ".txt"); export_vosviewer(gco, f); file.exists(f) })
cat("\n========== M8 ==========\n")
ck("store arrow", { p <- tempfile(); biblio_store(x_analise, p, "arrow"); nrow(biblio_load(p, "arrow")$works) })
ck("store guard", { p2 <- tempfile(fileext = ".duckdb"); biblio_store(x_analise, p2, "duckdb")
                    tryCatch(biblio_store(x_analise, p2, "duckdb"), error = function(e) conditionMessage(e)) })
ck("biblio_query", biblio_query({ p3 <- tempfile(fileext = ".duckdb"); biblio_store(x_analise, p3, "duckdb"); p3 },
                                "SELECT year, COUNT(*) AS obras FROM works GROUP BY year ORDER BY year"))
cat("\n========== M9 ==========\n")
if (inherits(x_openalex, "biblio_project")) {
  ck("openalex shape", vapply(x_openalex, nrow, integer(1)))
  ck("openalex obras", x_openalex$works[, c("title","year","source","cited_by_count")])
} else cat("openalex indisponivel\n")
ck("fetch_opencitations", fetch_opencitations("10.1038/nature12373")[1:3, ])
cat("\n========== M10 ==========\n")
ck("python_backend_status", python_backend_status())
ck("to_biblium", to_biblium(x_analise)[1:2, ])
ck("biblium_compare_groups", biblium_compare_groups(x_analise, g_per, entity = "keyword", permutations = 499, seed = SEED))
ck("validate_biblium", validate_biblium(x_analise, g_per, entity = "keyword", permutations = 499, seed = SEED)$comparison)
cat("\n========== M11 ==========\n")
ck("llm_configure", llm_configure(provider = "ollama"))
ck("llm_status", llm_status(verbose = FALSE))
ck("semantic_search erro", tryCatch(semantic_search(x_analise, "silicon"), error = function(e) conditionMessage(e)))
cat("\n========== M12 ==========\n")
pl <- form_plan(analyses = c("health","descriptive","temporal"), seed = SEED)
ck("validate_plan", validate_plan(pl))
ck("run_plan", names(run_plan(pl, x_analise)))
ck("biblio_report", { f <- file.path(tempdir(), "rel.md"); biblio_report(x_analise, f); readLines(f, n = 4) })
ck("export_biblio", { f <- tempfile(fileext = ".csv"); export_biblio(x_analise, f, "csv"); file.exists(f) })
ck("to_bibliometrix", dim(to_bibliometrix(x_analise)))
